accounts/urls.py
from django.urls import path
from . import views
app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('login/', views.MyLoginView.as_view(), name="login"),
    path('logout/', views.MyLogoutView.as_view(), name="logout"),
    path('profile/', views.UserProfileView.as_view(), name="profile"),
    path('profile_change/', views.MyUserChangeView.as_view(), name="profile_change"),
    path('password_change/', views.MyPasswordChangeView.as_view(),
         name="password_change"),
    path('password_change_done/', views.MyPasswordChangeDoneView.as_view(),
         name="password_change_done"),
    path('password_reset/', views.MyPasswordResetView.as_view(),
         name="password_reset"),
    path('password_reset_done/', views.MyPasswordResetDoneView.as_view(),
         name="password_reset_done"),
    path('password_reset_<uidb64>_<token>/', views.MyPasswordResetConfirmView.as_view(),
         name="password_reset_confirm"),
    path('password_reset_complete/', views.MyPasswordResetCompleteView.as_view(),
         name="password_reset_complete"),
]

api/urls.py
from django.urls import path
from . import views
# from django.views.decorators.csrf import csrf_exempt

app_name = 'api'

urlpatterns = [
    path('v1/vote/', views.CreateVoteView.as_view(), name='create_vote'),
]

board/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

app_name = "board"
urlpatterns = [
    path('', views.index, name="index"),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('create/', views.create, name='create'),
    path('category/<str:url_code>/', views.CategoryView.as_view(), name='category'),
    path('terms/', TemplateView.as_view(template_name='base/terms.html'), name='terms'),
    path('policy/', TemplateView.as_view(template_name='base/policy.html'), name='policy'),
    path('about/', TemplateView.as_view(template_name='base/about.html'), name='about'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from board.sitemaps import ThreadSitemap, CategorySitemap
from base.sitemaps import BaseSitemap

sitemaps = {
    'topic': ThreadSitemap,
    'cateogry': CategorySitemap,
    'base': BaseSitemap,
}
urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include("board.urls")),
    path('api/', include('api.urls')),
    path('search/', include('search.urls')),
    path('', include('accounts.urls')),
    path('', include('django.contrib.auth.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

search/urls.py
from django.urls import path
from . import views

app_name = 'search'

urlpatterns = [
    path('', views.SearchResultView.as_view(), name='result'),
]

templates/base/about.html
{% extends 'base/base.html' %}
{% block title %}このサイトはなに？ - {{ block.super }}{% endblock %}
{% block content %}
<div class="ui grid stackable">
  <div class="eleven wide column">
    <div class="ui breadcrumb">
      <a href="{% url 'board:index' %}" class="section">TOP</a>
      <i class="right angle icon divider"></i>
      <a class="active section">このサイトはなに？</a>
    </div>
    <div class="ui segment">
      <div class="content">
        <div class="header"><h3>このサイトはなに？</h3></div>
        <p>このサイトはDjangoのサンプルアプリです。などなど</p>
        <p>...............</p>
        <p>...........</p>
        <p>.......</p>
      </div>
    </div>
  </div>
  {% include 'base/sidebar.html' %}
</div>
{% endblock %}

templates/base/base.html
{% load static %}
<!DOCTYPE html>

<head>
  <meta charset="UTF-8">
  <meta http-equiv="content-language" content="ja">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  {% block meta_tag %}{% endblock %}
  <link href="{% static 'css/semantic.css' %}" rel="stylesheet">
  {% block css %}{% endblock %}
  <title>
      {% block title %}3ちゃんねる{% endblock %}
  </title>
</head>

<body>
  <div class="ui stackable inverted menu">
    <a href="{% url 'board:index' %}" class="header item">
        3ちゃんねる
    </a>
    <a class="item" href="{% url 'board:about' %}">
        このサイトはなに？
    </a>
    <div class="right menu">
        {% if user.is_authenticated %}
        <!-- ログインしているとき -->
        <span class='item'>name : {{ user }}</span>
        <a class="item" href="{% url 'board:index' %}">トップ</a>
        <a class="item" href="{% url 'board:create' %}">スレッド作成</a>
        <a class="item" href="{% url 'accounts:profile' %}">ユーザー情報</a>
        <a class="item" href="{% url 'accounts:logout' %}">ログアウト</a>
        {% else %}
        <!-- ログインしていないとき -->
        <a class="item" href="{% url "accounts:login" %}">ログイン</a>
        <a class="item" href="{% url "accounts:signup" %}">ユーザー登録</a>
        {% endif %}
    </div>
  </div>

  <div class="ui container" style="min-height:100vh;">
      {% block content %}
      {% endblock %}
  </div>
  <div class="ui inverted stackable footer segment">
    <div class="ui container center aligned">
      <div class="ui horizontal inverted small divided link list">
        <a class="item" href='{% url "board:index" %}'>© 2022 3ちゃんねる</a>
        <a class="item" href='{% url "board:terms" %}'>利用規約</a>
        <a class="item" href='{% url "board:policy" %}'>プライバシーポリシー</a>
      </div>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
  <script type="text/javascript" src="{% static 'js/semantic.js' %}"></script>
  {% block js %}{% endblock %}
</body>

templates/base/pagination.html
{% if is_paginated %}
<div class="ui basic segment center aligned">
    <div class="ui pagination menu">
    <!--左矢印-->
    {% if page_obj.has_previous %}
        <a class="item" href="?p={{page_obj.previous_page_number}}"><i class="chevron left icon"></i></a>
    {% else %}
        <a class="disabled item"><i class="chevron left icon"></i></a>
    {% endif %}
    <!--//左矢印-->
    <!--ページ番号-->
    {% for link_page in page_obj.paginator.page_range %}
        {% if link_page == page_obj.number %}
            <a class="disabled item">{{link_page}}</a>
        {% else %}
            <a class="item" href="?p={{link_page}}">{{link_page}}</a>
        {% endif %}
    {% endfor %}
    <!--//ページ番号-->
    <!--右矢印-->
    {% if page_obj.has_next %}
        <a class="item" href="?p={{page_obj.next_page_number}}"><i class="chevron right icon"></i></a>
    {% else %}
        <a class="disabled item"><i class="chevron right icon"></i></a>
    {% endif %}
    <!--//右矢印-->
    </div>
</div>
{% endif %}

templates/base/policy.html
{% extends 'base/base.html' %}
{% block title %}プライバシーポリシー - {{ block.super }}{% endblock %}
{% block content %}
<div class="ui grid stackable">
  <div class="eleven wide column">
    <div class="ui breadcrumb">
      <a href="{% url 'board:index' %}" class="section">TOP</a>
      <i class="right angle icon divider"></i>
      <a class="active section">プライバシーポリシー</a>
    </div>
    <div class="ui segment">
      <div class="content">
        <div class="header"><h3>プライバシーポリシー</h3></div>
        <p>あんなことやこんなことに情報を使います。などなど</p>
        <p>...............</p>
        <p>...........</p>
        <p>.......</p>
      </div>
    </div>
  </div>
  {% include 'base/sidebar.html' %}
</div>
{% endblock %}

templates/base/sidebar.html
{% load threadtags %}
<div class="five wide column">
  <form action="{% url 'search:result' %}" method="GET">
    <div class="ui action input" style="width: 100%;">
        <input type="text" placeholder="検索" value="{{query}}" name="q">
        <button type="submit" class="ui button"><i class="search icon"></i></button>
    </div>
  </form> 
  <div class="ui items">
      <div class="item">
          <a href="{% url 'board:create' %}" class="ui fluid teal button">トピックを作成</a>
      </div>
  </div>
  <div class="ui segment">
      <div class="content">
          <div class="header"><h4>カテゴリー</h4></div>
          {% categorytag %}
      </div>
  </div>
</div>

templates/base/terms.html
{% extends 'base/base.html' %}
{% block title %}利用規約 - {{ block.super }}{% endblock %}
{% block content %}

<div class="ui grid stackable">
  <div class="eleven wide column">
    <div class="ui breadcrumb">
      <a href="{% url 'board:index' %}" class="section">TOP</a>
      <i class="right angle icon divider"></i>
      <a class="active section">利用規約</a>
    </div>
    <div class="ui segment">
      <div class="content">
        <div class="header">
          <h3>利用規約</h3>
        </div>
        <p>あんなことやこんなことを守って下さい。などなど</p>
        <p>...............</p>
        <p>...........</p>
        <p>.......</p>
      </div>
    </div>
  </div>
  {% include 'base/sidebar.html' %}
</div>
{% endblock %}