api/urls.py
from django.urls import path
from . import views
# from django.views.decorators.csrf import csrf_exempt

app_name = 'api'

urlpatterns = [
    path('v1/vote/', views.CreateVoteView.as_view(), name='create_vote'),
]

board/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

app_name = "board"
urlpatterns = [
    path('', views.index, name="index"),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('create/', views.create, name='create'),
    path('category/<str:url_code>/', views.CategoryView.as_view(), name='category'),
    path('terms/', TemplateView.as_view(template_name='base/terms.html'), name='terms'),
    path('policy/', TemplateView.as_view(template_name='base/policy.html'), name='policy'),
    path('about/', TemplateView.as_view(template_name='base/about.html'), name='about'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from board.sitemaps import ThreadSitemap, CategorySitemap
from base.sitemaps import BaseSitemap

sitemaps = {
    'topic': ThreadSitemap,
    'cateogry': CategorySitemap,
    'base': BaseSitemap,
}
urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include("board.urls")),
    path('api/', include('api.urls')),
    path('search/', include('search.urls')),
    path('', include('accounts.urls')),
    path('', include('django.contrib.auth.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

board/models.py
from django.db import models
from accounts.models import User
from django.core.validators import FileExtensionValidator

# トピックのステータス一覧
TOPIC_STATUS_CHOICE = (
    (0, '公開'),
    (1, '非公開'),
    (2, '承認待ち'),
)

# トピックのステータス一覧
COMMENT_STATUS_CHOICE = (
    (0, '公開'),
    (1, '非公開'),
)


class ThreadManager(models.Manager):
    # Thread操作に関する処理を追加
    pass


class CommentManager(models.Manager):
    # Comment操作に関する処理を追加
    def create_comment(self, created_by, comment, thread_id, image=None):
        comment = self.model(
            created_by=created_by,
            comment=comment,
            image=image
        )
        comment.thread = Thread.objects.get(id=thread_id)
        comment.no = self.filter(thread_id=thread_id).count() + 1
        comment.save()


class CategoryManager(models.Manager):
    # Category操作に関する処理を追加
    pass


class VoteManager(models.Manager):
    def create_vote(self, ip_address, comment_id):
        vote = self.model(
            ip_address=ip_address,
            comment_id=comment_id
        )
        try:
            vote.save()
        except:
            return False
        return True


class Category(models.Model):
    name = models.CharField(
        'カテゴリー名',
        max_length=50,
    )
    url_code = models.CharField(
        'URLコード',
        max_length=50,
        null=True,
        blank=False,
        unique=True,
    )
    sort = models.IntegerField(
        verbose_name='ソート',
        default=0,
    )
    objects = CategoryManager()

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'category'


class Thread(models.Model):

    # カラム
    title = models.CharField(
        verbose_name='タイトル', blank=False, null=False, max_length=150)
    content = models.TextField(
        verbose_name='内容', blank=True, null=True)
    created_by = models.ForeignKey(
        User, verbose_name='投稿者', on_delete=models.PROTECT)
    category = models.ForeignKey(
        Category,  verbose_name='カテゴリー', on_delete=models.PROTECT, null=True, blank=False)
    status = models.IntegerField(
        verbose_name='トピックのステータス', default=0, choices=TOPIC_STATUS_CHOICE)
    created_at = models.DateTimeField(
        verbose_name='作成日時', auto_now_add=True)
    updated_at = models.DateTimeField(
        verbose_name='更新日時', auto_now=True)

    objects = ThreadManager()

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'thread'


class Comment(models.Model):

    # カラム
    id = models.BigAutoField(
        primary_key=True)
    no = models.IntegerField(default=0)
    comment = models.TextField(
        verbose_name='コメント', blank=False, null=False)
    image = models.ImageField(
        verbose_name='投稿画像',
        validators=[FileExtensionValidator(['jpg', 'png'])],
        upload_to='images/%Y/%m/%d/', null=True, blank=True,
    )
    created_by = models.ForeignKey(
        User, verbose_name='投稿者', on_delete=models.PROTECT)
    thread = models.ForeignKey(
        Thread, verbose_name='スレッド', on_delete=models.CASCADE)
    status = models.IntegerField(
        verbose_name='コメントのステータス', default=0, choices=COMMENT_STATUS_CHOICE)
    created_at = models.DateTimeField(
        verbose_name='作成日時', auto_now_add=True)
    updated_at = models.DateTimeField(
        verbose_name='更新日時', auto_now=True)

    objects = CommentManager()

    def __str__(self):
        return self.message

    class Meta:
        db_table = 'comment'


class Vote(models.Model):
    comment = models.ForeignKey(
        Comment,
        on_delete=models.CASCADE,
        null=True,
    )
    ip_address = models.CharField(
        'IPアドレス',
        max_length=50,
    )

    objects = VoteManager()

    def __str__(self):
        return '{}-{}'.format(self.comment.topic.title, self.comment.no)

    class Meta:
        db_table = 'vote'

board/forms.py
from django.forms import ModelForm
from .models import Thread, Comment


class ThreadForm(ModelForm):
    class Meta:
        # モデルを指定
        model = Thread
        # フォームとして表示したいカラムを指定
        fields = [
            'title',
            'category',
            'content',
            # 'created_by',
        ]

        def __init__(self, *args, **kwargs):
            # kwargs.setdefault('label_suffix', '')
            super().__init__(*args, **kwargs)
            # self.fields['title'].widget.attrs['class'] = 'huga'
            self.fields['category'].empty_label = '選択して下さい'
            #self.fields['created_by'].widget.attrs['value'] = '匿名'


class CommentForm(ModelForm):
    class Meta:
        # モデルを指定
        model = Comment
        # フォームとして表示したいカラムを指定
        fields = ("comment", "image")

    def __init__(self, *args, **kwargs):
        kwargs.setdefault('label_suffix', '')
        super().__init__(*args, **kwargs)
        # self.fields['user_name'].widget.attrs['value'] = '名無し'

    def save_with_thread(self, id, user, commit=True):
        comment = self.save(commit=False)
        # threadにログイン中ユーザー情報を追加
        comment.thread = Thread.objects.get(id=id)
        comment.no = Comment.objects.filter(id=id).count() + 1
        comment.created_by = user
        if commit:
            comment.save()
        return comment

board/views.py
from django.utils import timezone
from django.shortcuts import get_object_or_404, render, redirect
from django.views import View, generic
from .models import Category, Thread, Comment
from .forms import ThreadForm, CommentForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.db.models import Count
import logging
from django.urls import reverse_lazy
from django.http import HttpResponse
from django.core.mail import send_mail, EmailMessage
from django.template.loader import get_template


class BoardListView(LoginRequiredMixin, generic.ListView):
    template_name = 'board/index.html'
    queryset = Thread.objects.all().order_by('-created_at')
    context_object_name = 'threads'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.new_list = []

    def get_queryset(self):
        thread_list = Thread.objects.order_by('-created_at')
        self.new_list = self._make_new_list(thread_list)
        return thread_list

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['new_list'] = self.new_list
        return ctx

    def _make_new_list(self, thread_list):
        def pickup_topic(thread):
            now = timezone.now()
            diff = (now - thread.created_at).total_seconds() / (60 * 60)
            if diff > 1:
                return False
            else:
                return True
        # ログ出力
        logger = logging.getLogger(__name__)
        logger.info("スレッドを表示")
        return list(map(lambda x: x.id, filter(pickup_topic, thread_list)))


index = BoardListView.as_view()


class CategoryView(LoginRequiredMixin, generic.ListView):
    template_name = 'board/category.html'
    context_object_name = 'threads'
    paginate_by = 1  # 1ページに表示するオブジェクト数 サンプルのため1にしています
    page_kwarg = 'p'  # GETでページ数を受けるパラメータ名。指定しないと'page'がデフォルト

    def get_queryset(self):
        return Thread.objects.filter(category__url_code=self.kwargs['url_code'])

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['category'] = get_object_or_404(
            Category, url_code=self.kwargs['url_code'])
        return ctx


class BoardDetailView(LoginRequiredMixin, generic.FormView):
    template_name = 'board/detail.html'
    form_class = CommentForm

    def form_valid(self, form):
        # comment = form.save(commit=False)  # 保存せずオブジェクト生成する
        # comment.thread = Thread.objects.get(id=self.kwargs['pk'])
        # comment.no = Comment.objects.filter(
        #     thread=self.kwargs['pk']).count() + 1
        # comment.created_by = self.request.user
        # comment.save()
        # コメント保存のためsave_with_threadメソッドを呼ぶ
        Comment.objects.create_comment(
            created_by=self.request.user,
            comment=form.cleaned_data['comment'],
            thread_id=self.kwargs['pk'],
            image=form.cleaned_data['image']
        )
        form.save_with_thread(self.kwargs.get('pk'), self.request.user)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('board:detail', kwargs={'pk': self.kwargs['pk']})

    def get_context_data(self):
        ctx = super().get_context_data()
        ctx['thread'] = Thread.objects.get(id=self.kwargs['pk'])
        ctx['comments'] = Comment.objects.filter(
            thread=self.kwargs['pk']).annotate(vote_count=Count('vote')).order_by('no')
        return ctx


detail = BoardDetailView.as_view()


# class BoardCreateView(LoginRequiredMixin, generic.CreateView):
#     template_name = 'board/create.html'
#     form_class = ThreadForm
#     model = Thread
#     success_url = reverse_lazy('board:index')

#     def form_valid(self, form):
#         ctx = {'form': form}
#         if self.request.POST.get('next', '') == 'confirm':
#             return render(self.request, 'board/create_confirm.html', ctx)
#         if self.request.POST.get('next', '') == 'back':
#             return render(self.request, 'board/create.html', ctx)
#         if self.request.POST.get('next', '') == 'create':
#             # DBに登録する準備を行う
#             thread = form.save(commit=False)
#             # threadにログイン中ユーザー情報を追加
#             thread.created_by = self.request.user
#             # 保存
#             thread.save()
#             # ログ出力
#             logger = logging.getLogger(__name__)
#             logger.info("スレッドを作成しました")
#             # メール送信処理
#             template = get_template('board/mail/board_mail.html')
#             mail_ctx = {
#                 'title': form.cleaned_data['title'],
#                 'created_by': self.request.user,
#                 'content': form.cleaned_data['content'],
#             }
#             # EmailMessage(
#             #     subject='トピック作成: ' + form.creaned_data['title'],
#             #     body=template.render(mail_ctx),
#             #     from_email='test@example.com',
#             #     to=['admin2@example.com'],
#             #     # cc=['admin2@example.com'],
#             #     # bcc=['admin3@example.com'],
#             # ).send()
#             return super().form_valid(form)
#         else:
#             # 正常動作ではここは通らない。エラーページへの遷移でも良い
#             return redirect(reverse_lazy('board:index'))


# create2 = BoardCreateView.as_view()


class BoardCreateViewBySession(LoginRequiredMixin, generic.FormView):
    template_name = 'board/create.html'
    form_class = ThreadForm

    def post(self, request, *args, **kwargs):
        ctx = {}
        if request.POST.get('next', '') == 'back':
            if 'input_data' in self.request.session:
                input_data = self.request.session['input_data']
                form = ThreadForm(input_data)
                ctx['form'] = form
            return render(request, self.template_name, ctx)

        elif request.POST.get('next', '') == 'create':
            if 'input_data' in request.session:
                form = self.form_class(request.session['input_data'])
                # DBに登録する準備を行う
                thread = form.save(commit=False)
                # threadにログイン中ユーザー情報を追加
                thread.created_by = self.request.user
                # 保存
                thread.save()
                # ログ出力
                logger = logging.getLogger(__name__)
                logger.info("スレッドを作成しました2")
                # メール送信処理は省略

                response = redirect(reverse_lazy('board:index'))
                response.set_cookie(
                    'categ_id', request.session['input_data']['category'])
                request.session.pop('input_data')  # セッションに保管した情報の削除
                return response

        elif request.POST.get('next', '') == 'confirm':
            form = ThreadForm(request.POST)
            if form.is_valid():
                ctx = {'form': form}
                # セッションにデータを保存
                input_data = {
                    'title': form.cleaned_data['title'],
                    'content': form.cleaned_data['content'],
                    'category': form.cleaned_data['category'].id,
                }
                request.session['input_data'] = input_data
                ctx['category'] = form.cleaned_data['category']
                return render(request, 'board/create_confirm.html', ctx)
            else:
                return render(request, self.template_name, {'form': form})

    def get_context_data(self):
        ctx = super().get_context_data()
        if 'categ_id' in self.request.COOKIES:
            form = ctx['form']
            form['category'].field.initial = self.request.COOKIES['categ_id']
            ctx['form'] = form
        return ctx


create = BoardCreateViewBySession.as_view()


class BoardUpdateView(LoginRequiredMixin, generic.edit.UpdateView):
    template_name = 'board/update.html'
    model = Thread
    fields = ['content', 'title', ]

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()

        if obj.created_by.id != self.request.user.id:
            raise PermissionDenied('You do not have permission to edit.')

        return super(BoardUpdateView, self).dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse_lazy('board:index')

    def get_form(self):
        form = super(BoardUpdateView, self).get_form()
        form.fields['title'].label = 'タイトル'
        form.fields['content'].label = '内容'
        return form


update = BoardUpdateView.as_view()


class DeleteView(LoginRequiredMixin, generic.edit.DeleteView):
    template_name = 'board/delete.html'
    model = Thread
    success_url = reverse_lazy('board:index')


delete = DeleteView.as_view()

templates/board/category.html
{% extends 'base/base.html' %}
{% block title %}{{category.name}} - {{ block.super }}{% endblock %}
{% block content %}
<div class="ui grid stackable">
  <div class="eleven wide column">
    <div class="ui breadcrumb">
      <a class="section">TOP</a>
      <a class="active section">{{category.name}}</a>
    </div>
    <div class="ui segment">
      <div class="content">
        <div class="header"><h3>{{category.name}}</h3></div>
        {% include 'base/pagination.html' %}
        <div class="ui divided items">
          {% if threads %}
          {% for thread in threads %}
          <div class="item">
            <div class="content">
              <div class="header">
                <a href="{% url 'board:detail' pk=thread.id %}"><h4>{{thread.title}}</h4></a>
              </div>
              <div class="meta">
                <span class="name">{{thread.created_by}}</span>
                <span class="date">{{thread.created_at}}</span>
              </div>
            </div>
          </div>
          {% endfor %}
          {% else %}
          <div class="ui warning message">トピックが存在しません</div>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
  {% include 'base/sidebar.html' %}
</div>
{% endblock %}

templates/board/create.html
{% extends 'base/base.html' %}
{% block title %}スレッド作成 - {{ block.super }}{% endblock %}
{% block content %}
<div class="ui grid stackable">
  <div class="eleven wide column">
    <div class="ui breadcrumb">
      <a href="{% url 'board:index' %}" class="section">TOP</a>
      <i class="right angle icon divider"></i>
      <a class="active section">スレッド作成</a>
    </div>
    <div class="ui segment">
      <div class="content">
        <div class="header">
          <h3>スレッド作成</h3>
        </div>
        <form class="ui form" action="{% url 'board:create' %}" method="POST">
          {% csrf_token %}
          {% for field in form %}
          <div class="field">{{field.label_tag}}{{field}}</div>
          {% for error in field.errors%}
          <p style="color: red;">{{error}}</p>
          {% endfor%}
          {% endfor %}
           <button type="submit" class="ui button" name="next" value="confirm">作成</button>
        </form>
        <div class="mt-3">
          <a href='JavaScript:history.back()'>戻る</a>
        </div>
      </div>
    </div>
  </div>
  {% include 'base/sidebar.html' %}
</div>
{% endblock %}

templates/board/create_confirm.html
{% extends 'base/base.html' %}
{% block title %}トピック作成 - {{ block.super }}{% endblock %}
{% block content %}
<div class="ui grid stackable">
  <div class="eleven wide column">
    <div class="ui breadcrumb">
      <a href="{% url 'board:index' %}" class="section">TOP</a>
      <i class="right angle icon divider"></i>
      <a class="active section">トピック作成</a>
    </div>
    <div class="ui segment">
      <div class="content">
        <div class="header"><h3>トピック作成</h3></div>
        <p>内容を確認してください</p>
        <table  class="ui celled table table table-hover" >
          <tr><td>タイトル</td><td>{{form.title.value}}</td></tr>
          <tr><td>カテゴリー</td><td>{{form.cleaned_data.category}}</td></tr>
          <tr><td>本文</td><td><pre>{{form.content.value}}</pre></td></tr>
        </table>
        <form class="ui form" action="{% url 'board:create' %}" method="POST">
          {% csrf_token %}
          <button class="ui button grey" type="submit" name="next" value="back">戻る</button>
          <button class="ui button orange" type="submit" name="next" value="create">作成</button>
        </form>
      </div>
    </div>
  </div>
  {% include 'base/sidebar.html' %}
</div>
{% endblock %}

templates/board/delete.html
{% extends 'base/base.html' %} {% block content %}

<h1>スレッドの削除</h1>
<p>以下を削除しますか?</p>
<p>{{ thread.title }}</p>
<p>{{ thread.content }}</p>
<p>{{ thread.created_by }}</p>
<p>{{ thread.created_at|date:"Y-m-j H:i:s" }}</p>

<form action="" method="post">
  {% csrf_token %}
  <a href="JavaScript:history.back()" class="btn btn-outline-primary">削除しないで戻る</a>
  <button type="submit" class="submit delete btn btn-danger">削除する</button>
</form>

{% endblock %}

templates/board/detail.html
{% extends 'base/base.html' %}
{% block title %}スレッド作成 - {{ block.super }}{% endblock %}
{% block content %}
{% load threadfilters %}
{% load static  %}
<div class="ui grid stackable">
  <div class="eleven wide column">
    <div class="ui breadcrumb">
      <a href="{% url 'board:index' %}" class="section">TOP</a>
      <i class="right angle icon divider"></i>
      <a href="{% url 'board:category' url_code=thread.category.url_code %}" class="section">{{thread.category.name}}</a>
      <i class="right angle icon divider"></i>
      <a class="active section">{{thread.title}}</a>
    </div>
    <div class="ui segment">
      <div class="content">
        <div class="header"><h3>{{thread.title}}</h3></div>
        <p>{{thread.created_by}} - {{thread.created_at}}</p>
        <div class="ui segment">
          <p><pre>{{thread.message}}</pre></p>
        </div>
      </div>
    </div>
    <!--コメント表示-->
    <div class="ui segment">
      {% if comments %}
      {% for comment in comments %}
      <div class="ui segment secondary">
        <p>{{comment.no}}. {{comment.created_by}}<br>{{comment.created_at}}</p>
        {% if comment.pub_flg %}
        <p style="color: #aaa">このコメントは非表示となりました。</p>
        {% else %}
        <p>{{comment.comment | comment_filter | safe}}</pre></p>
          {% if comment.image %}
          <a href="{{comment.image.url}}" target="_blank" rel="noopener noreferrer"><img src="{{comment.image.url}}" width=200px></a>
          {% endif %}
        <div class="ui right aligned vertical segment">
          <div class="vote_button" style="cursor: pointer;"data-comment-id="{{comment.id}}" data-count="{{comment.vote_count}}">
            <i class="heart outline icon"></i>
            <span class="vote_counter">
            {% if comment.vote_count > 0 %}{{comment.vote_count}}{% endif %}
            </span>
          </div>
        </div>
        {% endif %}
      </div>
      {% endfor %}
      {% else %}
      <div class="ui warning message"><p>まだコメントはありません</p></div>
      {% endif %}
    </div>
    <!--//コメント表示-->
    <!--コメント投稿-->
    <h4>コメント投稿</h4>
    <div class="ui segment">
      <form class="ui form" action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <button class="ui button orange" type="submit">コメント投稿</button>
      </form>
    </div>
    <!--//コメント投稿-->
  </div>
  {% include 'base/sidebar.html' %}
</div>
{% endblock %}
{% block js %}
<script src="{% static 'js/vote.js' %}" type='text/javascript'></script>
{% endblock %}

templates/board/index.html
{% extends "base/base.html" %}
{% block title %}3ちゃんねる - {{ block.super }}{% endblock %}
{% block content %}
<div class="ui grid stackable">
  <div class="eleven wide column">
    <div class="ui breadcrumb">
      <a class="section">TOP</a>
      <i class="right angle icon divider"></i>
      <a class="section">category</a>
      <i class="right angle icon divider"></i>
      <div class="active section">thread</div>
    </div>
    <div class="ui segment">
      <div class="content">
        <div class="header">
          <h3>新着スレッド</h3>
        </div>
        <div class="ui divided items">
          {% for thread in threads %}
          <div class="item">
            <div class="content">
              <div class="header">
                <a href="{% url "board:detail" thread.pk %}">
                  <h4>
                    {% if thread.id in new_list %}
                    <div class="ui violet horizontal label">new</div>
                    {% endif %}
                    {{thread.title}}
                  </h4>
                </a>
              </div>
              <p class="card-text">{{ thread.content }}</p>
              <div class="meta">
                <a href='{% url "board:update" thread.pk %}'>編集</a>
                <a href='{% url "board:delete" thread.pk %}'>削除</a>
              </div>
              <div class="meta">
                <span class="name">{{thread.created_by}}</span>
                <span class="date">{{thread.created_at}}</span>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
  {% include 'base/sidebar.html' %}
</div>
{% endblock %}

templates/board/update.html
{% extends "base/base.html" %}

{% block page_title %}スレッド編集{% endblock %}
{% block title %}スレッド編集{% endblock %}

{% block content %}
<form method="post" action='{% url "board:update" thread.pk %}'>
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="button">保存</button>
</form>
<div class="mt-3">
  <a href='JavaScript:history.back()' class='btn btn-outline-primary'>戻る</a>
</div>
{% endblock %}

templates/board/write.html
{% extends "base.html" %}

{% block page_title %}Write{% endblock %}
{% block title %}Write{% endblock %}

{% block content %}
    <form method="post" action="{% url 'board:write' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="button">投稿</button>
    </form>
{% endblock %}